name: Build Modified Magisk

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

env:
  NDK_VERSION: r26b

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Find configuration files
      run: |
        echo "Searching for configuration files..."
        find . -name "*.hpp" -o -name "*.h" -o -name "config.sh" | grep -E "(config|stub)" | head -10
        git grep -l "STUB_APK" || echo "No STUB_APK found"
        git grep -l "stub.apk" || echo "No stub.apk found"

    - name: Modify configuration
      run: |
        # 尝试修改可能的配置文件
        # 首先检查并修改 native/src/core/config.hpp
        if [ -f "native/src/core/config.hpp" ]; then
          echo "Modifying native/src/core/config.hpp"
          sed -i 's/^#define STUB_APK_RAW .*/#define STUB_APK_RAW ""/' native/src/core/config.hpp
        fi
        
        # 检查并修改 scripts/config.sh
        if [ -f "scripts/config.sh" ]; then
          echo "Modifying scripts/config.sh"
          sed -i 's/^STUB_APK=.*/STUB_APK=""/' scripts/config.sh
        fi
        
        # 显示修改结果
        echo "Modified content:"
        git grep -n "STUB_APK" || echo "STUB_APK not found after modification"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl wget zip unzip python3 python3-pip build-essential libssl-dev zlib1g-dev

    - name: Download and setup Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip
        unzip android-ndk-${{ env.NDK_VERSION }}-linux.zip -d /home/runner/
        echo "NDK_HOME=/home/runner/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_ENV
        echo "NDK=/home/runner/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_ENV

    - name: Set up Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        source $HOME/.cargo/env
        rustc --version

    - name: Build Magisk native binaries
      run: |  # 修改这里：使用 'native' 而不是 'binary'
        source $HOME/.cargo/env
        export NDK=/home/runner/android-ndk-${{ env.NDK_VERSION }}
        export NDK_HOME=/home/runner/android-ndk-${{ env.NDK_VERSION }}
        cd $GITHUB_WORKSPACE
        python3 build.py -v native  # 这里改为 'native'

    - name: List output files
      run: |
        find $GITHUB_WORKSPACE/out -type f -name "magisk*" | xargs ls -la

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: magisk-binaries
        path: |
          out/**/magisk
          out/**/magiskinit
          out/**/magiskboot
          out/**/magiskpolicy
        if-no-files-found: error
