name: Build Modified Magisk

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Find configuration files
      run: |
        echo "Searching for configuration files..."
        find . -name "*.hpp" -o -name "*.h" -o -name "config.sh" | grep -E "(config|stub)" | head -10
        git grep -l "STUB_APK" || echo "No STUB_APK found"
        git grep -l "stub.apk" || echo "No stub.apk found"

    - name: Modify configuration
      run: |
        # 尝试修改可能的配置文件
        # 首先检查并修改 native/src/core/config.hpp
        if [ -f "native/src/core/config.hpp" ]; then
          echo "Modifying native/src/core/config.hpp"
          sed -i 's/^#define STUB_APK_RAW .*/#define STUB_APK_RAW ""/' native/src/core/config.hpp
        fi
        
        # 检查并修改 scripts/config.sh
        if [ -f "scripts/config.sh" ]; then
          echo "Modifying scripts/config.sh"
          sed -i 's/^STUB_APK=.*/STUB_APK=""/' scripts/config.sh
        fi
        
        # 显示修改结果
        echo "Modified content:"
        git grep -n "STUB_APK" || echo "STUB_APK not found after modification"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl wget zip unzip python3 python3-pip build-essential libssl-dev zlib1g-dev

    - name: Set up Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        source $HOME/.cargo/env
        rustc --version

    - name: Setup NDK using Magisk script
      run: |
        source $HOME/.cargo/env
        cd $GITHUB_WORKSPACE
        # 使用 Magisk 的 build.py 来设置 NDK
        python3 build.py -v ndk

    - name: Build Magisk native binaries
      run: |
        source $HOME/.cargo/env
        cd $GITHUB_WORKSPACE
        # 使用 Magisk 管理的 NDK 来构建原生二进制文件
        python3 build.py -v native

    - name: Debug - List all files in out directory
      run: |
        echo "Listing all files in out directory:"
        find $GITHUB_WORKSPACE/out -type f 2>/dev/null | sort || echo "out directory does not exist or is empty"
        
        echo ""
        echo "Searching for magisk-related files anywhere:"
        find $GITHUB_WORKSPACE -name "*magisk*" -type f 2>/dev/null | sort || echo "No magisk files found"

    - name: Upload build artifacts (flexible)
      if: success() || failure()  # 即使构建失败也尝试上传
      uses: actions/upload-artifact@v4
      with:
        name: magisk-build-output
        path: |
          ${{ github.workspace }}/out/**
          ${{ github.workspace }}/build.log
        if-no-files-found: ignore
        retention-days: 1

    - name: Create and upload build log
      run: |
        # 创建构建日志
        echo "Build process completed at $(date)" > $GITHUB_WORKSPACE/build.log
        echo "GitHub Workspace: $GITHUB_WORKSPACE" >> $GITHUB_WORKSPACE/build.log
        echo "" >> $GITHUB_WORKSPACE/build.log
        echo "Directory structure:" >> $GITHUB_WORKSPACE/build.log
        ls -la $GITHUB_WORKSPACE/ >> $GITHUB_WORKSPACE/build.log 2>&1 || echo "Cannot list workspace" >> $GITHUB_WORKSPACE/build.log
        echo "" >> $GITHUB_WORKSPACE/build.log
        echo "Out directory contents:" >> $GITHUB_WORKSPACE/build.log
        ls -la $GITHUB_WORKSPACE/out/ >> $GITHUB_WORKSPACE/build.log 2>&1 || echo "Out directory does not exist" >> $GITHUB_WORKSPACE/build.log

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: ${{ github.workspace }}/build.log
        if-no-files-found: ignore
        retention-days: 7
